from .department import department_repo, DepartmentRepository
from .user import user_repo, UserRepository
from .category import category_repo, CategoryRepository
from .emission_factor import emission_factor_repo, EmissionFactorRepository
from .product_esg_profile import product_esg_profile_repo, ProductESGProfileRepository
from .goal import goal_repo, GoalRepository
from .carbon_transaction import carbon_transaction_repo, CarbonTransactionRepository
from .csr_activity import csr_activity_repo, CSRActivityRepository
from .employee_participation import employee_participation_repo, EmployeeParticipationRepository
from .challenge import challenge_repo, ChallengeRepository
from .challenge_participation import challenge_participation_repo, ChallengeParticipationRepository
from .badge import badge_repo, BadgeRepository
from .reward import reward_repo, RewardRepository
from .user_badge import user_badge_repo, UserBadgeRepository
from .policy import policy_repo, PolicyRepository
from .policy_acknowledgement import policy_acknowledgement_repo, PolicyAcknowledgementRepository
from .audit import audit_repo, AuditRepository
from .compliance_issue import compliance_issue_repo, ComplianceIssueRepository
from .department_score import department_score_repo, DepartmentScoreRepository
from .notification import notification_repo, NotificationRepository
from .setting import setting_repo, SettingRepository