from .carbon import CarbonEstimationInput, CarbonEstimationOutput
from .narrator import ReportNarratorInput, ReportNarratorOutput
from .anomaly import AnomalyDetectionInput, AnomalyDetectionOutput
from .challenge import ChallengeRecommendationInput, ChallengeRecommendationOutput
