import React, { useState } from 'react'
import { PageTransition } from '../components/ui/PageTransition'
import { GlassCard } from '../components/ui/GlassCard'
import { Button } from '../components/ui/Button'
import { CardSkeleton } from '../components/ui/Skeleton'
import { EmptyState } from '../components/ui/EmptyState'
import { ErrorBoundary } from '../components/ui/ErrorBoundary'
import { useGenerateNarrative, useDepartmentScores } from '../hooks/useQueries'
import { exportToPDF, exportToCSV } from '../lib/exports'
import { FileText, Download, Sparkles, Loader2 } from 'lucide-react'

export const Reports = () => {
  const { data: deptScores = [], isLoading } = useDepartmentScores()
  const generateNarrative = useGenerateNarrative()
  const [narrative, setNarrative] = useState<{ title?: string; executive_summary?: string; narrative_body?: string } | null>(null)

  const handleGenerate = async () => {
    const metrics = (deptScores as Array<{ score: number }>).reduce((acc: Record<string, number>, d, i) => {
      acc[`dept_${i}_score`] = d.score
      return acc
    }, {})
    const result = await generateNarrative.mutateAsync({ data_metrics: metrics, report_type: 'Quarterly ESG Report' })
    setNarrative(result?.structured_output || result)
  }

  return (
    <PageTransition className="max-w-6xl mx-auto space-y-8">
      <header className="flex justify-between items-end flex-wrap gap-4">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight" style={{ color: 'var(--color-text-primary)' }}>Reports</h1>
          <p className="mt-1 text-sm" style={{ color: 'var(--color-text-secondary)' }}>AI-generated ESG narratives and departmental analytics</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={() => exportToCSV(deptScores as Record<string, unknown>[], 'dept-scores')}>
            <Download className="w-4 h-4 mr-1" /> CSV
          </Button>
          <Button
            variant="primary"
            onClick={handleGenerate}
            disabled={generateNarrative.isPending}
            aria-busy={generateNarrative.isPending}
          >
            {generateNarrative.isPending ? (
              <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...</>
            ) : (
              <><Sparkles className="w-4 h-4 mr-2" /> Generate AI Report</>
            )}
          </Button>
        </div>
      </header>

      {/* AI Narrative Result */}
      {narrative && (
        <GlassCard>
          <div className="flex items-start justify-between mb-4">
            <div>
              <h2 className="text-lg font-semibold" style={{ color: 'var(--color-text-primary)' }}>{narrative.title ?? 'ESG Executive Report'}</h2>
              <p className="text-xs mt-1" style={{ color: 'var(--color-muted)' }}>Generated by EcoSphere AI &middot; LangGraph Narrator Agent</p>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => exportToPDF(narrative.title ?? 'ESG Report', [narrative as Record<string, unknown>], 'esg-report')}
              aria-label="Download report as PDF"
            >
              <Download className="w-4 h-4 mr-2" /> PDF
            </Button>
          </div>
          {narrative.executive_summary && (
            <div className="mb-4 p-4 rounded-lg bg-primary/5 border border-primary/10">
              <p className="text-xs font-semibold uppercase tracking-wide mb-2" style={{ color: 'var(--color-primary)' }}>Executive Summary</p>
              <p className="text-sm leading-relaxed" style={{ color: 'var(--color-text-primary)' }}>{narrative.executive_summary}</p>
            </div>
          )}
          {narrative.narrative_body && (
            <p className="text-sm leading-relaxed whitespace-pre-wrap" style={{ color: 'var(--color-text-secondary)' }}>{narrative.narrative_body}</p>
          )}
        </GlassCard>
      )}

      {/* Department Scores Table */}
      <ErrorBoundary>
        <GlassCard className="p-0 overflow-hidden">
          <div className="p-4 border-b" style={{ borderColor: 'var(--color-border)' }}>
            <h2 className="font-semibold" style={{ color: 'var(--color-text-primary)' }}>Department ESG Scores</h2>
          </div>
          {isLoading ? (
            <div className="p-4 space-y-4"><CardSkeleton /><CardSkeleton /></div>
          ) : (deptScores as unknown[]).length === 0 ? (
            <EmptyState icon={<FileText className="w-8 h-8" />} title="No department scores" description="Score data will appear after departments are configured." />
          ) : (
            <div className="divide-y" style={{ borderColor: 'var(--color-border)' }}>
              {(deptScores as Array<{ department_id: string; score: number; month: number; year: number }>).map((d, i) => (
                <div key={i} className="flex items-center gap-4 px-4 py-3 hover:bg-black/5 transition-colors">
                  <div className="flex-1">
                    <p className="text-sm font-medium" style={{ color: 'var(--color-text-primary)' }}>Dept ID: {d.department_id}</p>
                    <p className="text-xs" style={{ color: 'var(--color-muted)' }}>{d.month}/{d.year}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-24 h-1.5 rounded-full bg-black/10 overflow-hidden">
                      <div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.min(d.score, 100)}%` }} />
                    </div>
                    <span className="text-sm font-semibold" style={{ color: 'var(--color-text-primary)' }}>{d.score.toFixed(1)}</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </GlassCard>
      </ErrorBoundary>
    </PageTransition>
  )
}
