from .department import router as department_router
from .user import router as user_router
from .category import router as category_router
from .emission_factor import router as emission_factor_router
from .product_esg_profile import router as product_esg_profile_router
from .goal import router as goal_router
from .carbon_transaction import router as carbon_transaction_router
from .csr_activity import router as csr_activity_router
from .employee_participation import router as employee_participation_router
from .challenge import router as challenge_router
from .challenge_participation import router as challenge_participation_router
from .badge import router as badge_router
from .reward import router as reward_router
from .user_badge import router as user_badge_router
from .policy import router as policy_router
from .policy_acknowledgement import router as policy_acknowledgement_router
from .audit import router as audit_router
from .compliance_issue import router as compliance_issue_router
from .department_score import router as department_score_router
from .notification import router as notification_router
from .setting import router as setting_router